name: CI for Pull Requests

on:
  pull_request:
    branches:
      - main  # Run the workflow for PRs targeting the "main" branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the PR branch
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    # Step 3: Install MBT and dependencies
    - name: Install MBT and dependencies
      run: |
        npm install -g mbt
        npm install
    # Step 4: Install CF Cli
    - name: Install CF Cli
      run: |
         wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | gpg --dearmor -o /usr/share/keyrings/cli.cloudfoundry.org.gpg
         echo "deb [trusted=yes] https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
         sudo apt-get update
         sudo apt-get install cf8-cli
    # Step 6: Download and Install SAP BTP CLI
    - name: Install BTP CLI
      run: |
        dpkg --print-architecture
        curl -LJO https://tools.hana.ondemand.com/additional/btp-cli-linux-amd64-latest.tar.gz --cookie "eula_3_2_agreed=tools.hana.ondemand.com/developer-license-3_2.txt"
        tar -xzf btp-cli-linux-amd64-latest.tar.gz
        ls -a
        mv linux-amd64/btp /usr/local/bin
        chmod +x /usr/local/bin/btp
    - name: Verify BTP CLI Installation
      run: | 
        btp --version
         
    # Step 5: Install Multiapps Plugin
    - name: Install Multiapps Plugin
      run: |
        cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
        cf install-plugin multiapps -f
    # Step 6: Login to CF
    - name: Log in to Cloud Foundry
      run: |
        cf login -u ${{ secrets.CF_USERNAME }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ secrets.CF_SPACE }} -a ${{ secrets.CF_API }}
      
    # Step 7: Build the project
    - name: Build MTA Archive
      run: |
        mbt build 
    # Step 8: Verify MTA Archive built successfully
    - name: Deploy to CF
      run: |
        cf deploy ./mta_archives/arvato-cap-ws_1.0.0.mtar